spring:
  application.name: create-controller
  data:
    redis:
      host: "mptest.w.qiyi.redis"
      port: 6380
      password: "zMS2OOdbxQU7"
      database: 9
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
logging:
  level:
    aicreative.ai: DEBUG
  file:
    path: ./var/log
task:
  exec-strategy:
    task-type-strategy-map:
      CozeWorkflow:
        retry-cnt: 1
        timeout: 600000
proxy:
  coze:
    api:
      token: your-api-token
  huoshan:
    api:
      app-id: 6602608726
      token: KlRIInvV3aDWUhDqePBsbPRYYIFp6nDH
  deep-seek:
    api:
      key: your-api-key
